
format = """
[î‚²](#0B2918)\
$os\
$username\
[î‚°](bg:#244E30 fg:#0B2918)\
$directory\
[î‚°](fg:#244E30 bg:#4B713F)\
$git_branch\
$git_status\
[î‚°](fg:#4B713F bg:#5BAB3C)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[î‚°](fg:#5BAB3C bg:#C8F424)\
$docker_context\
$conda\
$pixi\
[î‚°](fg:#C8F424 bg:#F8FE29)\
$time\
[î‚° ](fg:#F8FE29)\
$line_break$character"""

palette = 'cyberpunk_yellowgreen'

[palettes.cyberpunk_yellowgreen]
color1 = '#0B2918'
color2 = '#244E30'
color3 = '#4B713F'
color4 = '#5BAB3C'
color5 = '#C8F424'
color6 = '#F8FE29'

[os]
disabled = false
style = "bg:#0B2918 fg:#F8FE29"

[os.symbols]
Windows = "âŠ"
Ubuntu = "ïŒ›"
SUSE = "ïŒ”"
Raspbian = "ïŒ•"
Mint = "ïŒ‚"
Macos = "ğŸ"
Manjaro = "ïŒ’"
Linux = "ğŸ§"
Gentoo = "ïŒ"
Fedora = "ïŒŠ"
Alpine = "ïŒ€"
Amazon = "ï‰°"
Android = "ğŸ¤–"
Arch = "ïŒƒ"
Artix = "ïŒƒ"
EndeavourOS = "ï†—"
CentOS = "ïŒ„"
Debian = "ïŒ†"
Redhat = "ïŒ–"
RedHatEnterprise = "ïŒ–"
Pop = "ïŒª"


[username]
show_always = true
style_user = "bg:#0B2918 fg:#F8FE29"
style_root = "bg:#0B2918 fg:#F8FE29"
format = '[ $user ]($style)'

[directory]
style = "fg:#F8FE29 bg:#244E30"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "â€¦/"
truncate_to_repo = false

[directory.substitutions]
"Documents" = "ğŸ“„ "
"Downloads" = "ğŸ“¥ "
"Music" = "ğŸµ "
"Pictures" = "ğŸ–¼ï¸ "
"Developer" = "ğŸ’» "

[git_branch]
symbol = "ğŸŒ± "
style = "bg:#4B713F"
format = '[[ $symbol $branch ](fg:#F8FE29 bg:#4B713F)]($style)'

[git_status]
style = "bg:#4B713F"
format = '[[($all_status$ahead_behind )](fg:#F8FE29 bg:#4B713F)]($style)'

[nodejs]
symbol = "â¬¢ "
style = "bg:#5BAB3C"
format = '[[ $symbol( $version) ](fg:#F8FE29 bg:#5BAB3C)]($style)'

[c]
symbol = "C "
style = "bg:#5BAB3C"
format = '[[ $symbol( $version) ](fg:#F8FE29 bg:#5BAB3C)]($style)'

[cpp]
symbol = "C++ "
style = "bg:#5BAB3C"
format = '[[ $symbol( $version) ](fg:#F8FE29 bg:#5BAB3C)]($style)'

[rust]
symbol = "ğŸ¦€ "
style = "bg:#5BAB3C"
format = '[[ $symbol( $version) ](fg:#F8FE29 bg:#5BAB3C)]($style)'

[golang]
symbol = "ğŸ¹ "
style = "bg:#5BAB3C"
format = '[[ $symbol( $version) ](fg:#F8FE29 bg:#5BAB3C)]($style)'

[php]
symbol = "ğŸ˜ "
style = "bg:#5BAB3C"
format = '[[ $symbol( $version) ](fg:#F8FE29 bg:#5BAB3C)]($style)'

[java]
symbol = "â˜• "
style = "bg:#5BAB3C"
format = '[[ $symbol( $version) ](fg:#F8FE29 bg:#5BAB3C)]($style)'

[kotlin]
symbol = "Kotlin "
style = "bg:#5BAB3C"
format = '[[ $symbol( $version) ](fg:#F8FE29 bg:#5BAB3C)]($style)'

[haskell]
symbol = "Î» "
style = "bg:#5BAB3C"
format = '[[ $symbol( $version) ](fg:#F8FE29 bg:#5BAB3C)]($style)'

[python]
symbol = "ğŸ "
style = "bg:#5BAB3C"
format = '[[ $symbol( $version)( \($virtualenv\)) ](fg:#F8FE29 bg:#5BAB3C)]($style)'

[docker_context]
symbol = "ğŸ³ "
style = "bg:#C8F424"
format = '[[ $symbol( $context) ](fg:#244E30 bg:#C8F424)]($style)'

[conda]
symbol = "Conda "
style = "bg:#C8F424"
format = '[[ $symbol( $environment) ](fg:#244E30 bg:#C8F424)]($style)'

[pixi]
symbol = "Pixi "
style = "bg:#C8F424"
format = '[[ $symbol( $version)( $environment) ](fg:#0B2918 bg:#C8F424)]($style)'

[package]
symbol = "ğŸ“¦ "
style = "bg:#C8F424"
format = '[[ $symbol( $version) ](fg:#0B2918 bg:#C8F424)]($style)'

[swift]
symbol = "Swift "
style = "bg:#C8F424"
format = '[[ $symbol( $version) ](fg:#0B2918 bg:#C8F424)]($style)'

[elixir]
symbol = "ğŸ’§ "
style = "bg:#C8F424"
format = '[[ $symbol( $version) ](fg:#0B2918 bg:#C8F424)]($style)'

[erlang]
symbol = "Erlang "
style = "bg:#C8F424"
format = '[[ $symbol( $version) ](fg:#0B2918 bg:#C8F424)]($style)'

[scala]
symbol = "Scala "
style = "bg:#C8F424"
format = '[[ $symbol( $version) ](fg:#0B2918 bg:#C8F424)]($style)'

[perl]
symbol = "ğŸª "
style = "bg:#C8F424"
format = '[[ $symbol( $version) ](fg:#0B2918 bg:#C8F424)]($style)'

[ruby]
symbol = "ğŸ’ "
style = "bg:#C8F424"
format = '[[ $symbol( $version) ](fg:#0B2918 bg:#C8F424)]($style)'

[dotnet]
symbol = ".NET "
style = "bg:#C8F424"
format = '[[ $symbol( $version) ](fg:#0B2918 bg:#C8F424)]($style)'

# [typescript]
# [angular]
# [vuejs]
# [react]
# [quarto]
# [terraform]

[time]
disabled = false
time_format = "%R"
style = "bg:#F8FE29"
format = '[[ ğŸ•’ $time ](fg:#0B2918 bg:#F8FE29)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[â†ª](bold fg:#5BAB3C)'
error_symbol = '[âŒ](bold fg:#0B2918)'
vimcmd_symbol = '[â®œ](bold fg:#5BAB3C)'
vimcmd_replace_one_symbol = '[â®œ](bold fg:#C8F424)'
vimcmd_replace_symbol = '[â®œ](bold fg:#C8F424)'
vimcmd_visual_symbol = '[â®œ](bold fg:#F8FE29)'
